=== raffaine/soaexpert-classes/DeMacho/schemas/DeMacho.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.example.org/DeMacho" xmlns:tns="http://www.example.org/DeMacho" elementFormDefault="qualified">
	<!--ENTIDADES - INICIO-->
	<complexType name="Usuario">
		<sequence>
			<element name="id" type="int"/>
			<element name="nome" type="string"/>
			<element name="nomeCompleto" type="string"/>
			<element name="email" type="string"/>
			<element name="dataNascimento" type="date"/>
			<element name="sexo" type="tns:Sexo"/>
			<element name="statusConta" type="tns:StatusConta"/>
			<element name="status" type="tns:Status"/>
			<element name="foto" type="base64Binary"/>
		</sequence>
	</complexType>
	
	<complexType name="Amigos">
		<sequence>
			<element name="usuario" type="tns:Usuario"/>
			<element name="amigo" type="tns:Usuario" minOccurs="0" maxOccurs="unbounded"/>
		</sequence>
	</complexType>
	
	<complexType name="Postagem">
		<sequence>
			<element name="usuario" type="tns:Usuario"/>
			<element name="corpo" type="string"/>
			<element name="anexo" type="tns:Anexo" minOccurs="0" maxOccurs="3"/>
		</sequence>
	</complexType>
	
	<complexType name="Anexo">
		<sequence>
			<element name="id" type="int"/>
			<element name="nome" type="string"/>
			<element name="comentario" type="string"/>
			<element name="url" type="anyURI"/>
			<element name="imagem" type="base64Binary"/>
		</sequence>
	</complexType>
	
	<complexType name="Timeline">
		<sequence>
			<element name="usuario" type="tns:Usuario"/>
			<element name="postagem" type="tns:Postagem" minOccurs="0" maxOccurs="unbounded"/>
		</sequence>
	</complexType>
	
	<complexType name="Favorito">
		<sequence>
			<element name="usuario" type="tns:Usuario"/>
			<element name="postagem" type="tns:Postagem" minOccurs="0" maxOccurs="unbounded"/>
		</sequence>
	</complexType>
	<!--ENTIDADES - FIM-->
	
	<!--VALUE OBJECTS - INICIO-->
	<simpleType name="Sexo">
		<restriction base="string">
			<enumeration value="FEMININO"/>
			<enumeration value="MASCULINO"/>
		</restriction>
	</simpleType>
	
	<simpleType name="StatusConta">
		<restriction base="string">
			<enumeration value="ATIVO"/>
			<enumeration value="INATIVO"/>
			<enumeration value="PENDENTE"/>
		</restriction>
	</simpleType>
	
	<simpleType name="Status">
		<restriction base="string">
			<enumeration value="ONLINE"/>
			<enumeration value="OFFLINE"/>
			<enumeration value="AUSENTE"/>
			<enumeration value="OCUPADO"/>
		</restriction>
	</simpleType>
	<!--VALUE OBJECTS - FIM-->
	
	<element name="usuario" type="tns:Usuario"/>
	<element name="amigos" type="tns:Amigos"/>
	<element name="postagem" type="tns:Postagem"/>
	<element name="timeline" type="tns:Timeline"/>
	<element name="favorito" type="tns:Favorito"/>
	<element name="anexo" type="tns:Anexo"/>
	
</schema>

=== raffaine/soaexpert-classes/DeMacho/schemas/amigos.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:amigos xmlns:tns="http://www.example.org/DeMacho" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.example.org/DeMacho DeMacho.xsd ">
  <tns:usuario>
    <tns:id>0</tns:id>
    <tns:nome>tns:nome</tns:nome>
    <tns:nomeCompleto>tns:nomeCompleto</tns:nomeCompleto>
    <tns:email>tns:email</tns:email>
    <tns:dataNascimento>2001-01-01</tns:dataNascimento>
    <tns:sexo>FEMININO</tns:sexo>
    <tns:statusConta>ATIVO</tns:statusConta>
    <tns:status>ONLINE</tns:status>
    <tns:foto>MA==</tns:foto>
  </tns:usuario>
  <tns:amigo>
	<tns:id>2</tns:id>
    <tns:nome>amigo</tns:nome>
    <tns:nomeCompleto>amigo completo</tns:nomeCompleto>
    <tns:email>amigo@gmail.com</tns:email>
    <tns:dataNascimento>2001-01-01</tns:dataNascimento>
    <tns:sexo>FEMININO</tns:sexo>
    <tns:statusConta>ATIVO</tns:statusConta>
    <tns:status>ONLINE</tns:status>
    <tns:foto>MA==</tns:foto>  	
  </tns:amigo>
</tns:amigos>

=== raffaine/soaexpert-classes/DeMacho/schemas/timeline.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:timeline xmlns:tns="http://www.example.org/DeMacho" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.example.org/DeMacho DeMacho.xsd ">
  <tns:usuario>
    <tns:id>0</tns:id>
    <tns:nome>tns:nome</tns:nome>
    <tns:nomeCompleto>tns:nomeCompleto</tns:nomeCompleto>
    <tns:email>tns:email</tns:email>
    <tns:dataNascimento>2001-01-01</tns:dataNascimento>
    <tns:sexo>FEMININO</tns:sexo>
    <tns:statusConta>ATIVO</tns:statusConta>
    <tns:status>ONLINE</tns:status>
    <tns:foto>MA==</tns:foto>
  </tns:usuario>
</tns:timeline>
